#!/usr/bin/env python3
"""Generates src/ui/icons_material.h from third_party/material-icons/_data/codepoints.json:
one UTF-8 string constant per icon we use (ICON_MD_<NAME>) plus the font range."""
import json, sys
ICONS = ["face", "person", "accessibility_new", "straighten", "record_voice_over", "movie", "check_circle", "check",
         "mic", "mic_off", "graphic_eq", "play_arrow", "pause", "stop", "skip_previous", "skip_next", "loop", "folder_open", "file_download", "save", "ios_share",
         "3d_rotation", "add_location_alt", "open_with", "grid_on", "visibility", "visibility_off", "label", "label_off",
         "center_focus_strong", "flip", "rotate_left", "rotate_right", "swap_vert", "auto_fix_high", "autorenew",
         "undo", "redo", "brush", "flip", "save_alt", "restart_alt", "tune", "circle", "warning", "error", "info", "refresh", "close", "menu", "add", "delete", "graphic_eq",
         "psychology", "rule", "sensors", "animation", "face_retouching_natural", "vertical_align_center", "highlight_alt", "front_hand", "sync", "mood", "remove_red_eye", "gradient", "file_upload", "thermostat"]
def main(src, dst):
    cp = json.load(open(src))
    lo, hi = 0xe000, 0xf8ff
    lines = ["// Generated by tools/gen_icon_header.py from third_party/material-icons (Apache-2.0). Do not edit.",
             "#pragma once", "#define ICON_MIN_MD 0x%04x" % lo, "#define ICON_MAX_MD 0x%04x" % hi]
    for n in ICONS:
        if n not in cp: print("missing icon", n, file=sys.stderr); continue
        c = int(cp[n], 16)
        u8 = chr(c).encode('utf-8')
        lines.append('#define ICON_MD_%s "%s"  // %s U+%04X' % (n.upper(), ''.join('\\x%02x' % b for b in u8), n, c))
    open(dst, 'w').write('\n'.join(lines) + '\n'); print('wrote', dst)
if __name__ == '__main__': main(sys.argv[1], sys.argv[2])
